# Supabase Configuration

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# Database settings

[storage]
# Storage buckets configuration

[auth]
enable_anonymous_sign_ins = true
enable_signup = true

[auth.external.apple]
enabled = false

[auth.external.google]
enabled = false